-- ============================================
-- Seed 8 Bremer Suits Products
-- Run after 001_products.sql migration
-- ============================================

-- Clear existing products (optional — remove if you want to keep existing data)
-- DELETE FROM products;

INSERT INTO products (title, category, fabric, price, numeric_price, image, tag, description, sale_price, original_price, colors, sizes, sku, status, stock)
VALUES
  (
    'Navy Pinstripe 3-Piece',
    'Bespoke Suits',
    'Super 150s Wool',
    'KES 15,000',
    15000.00,
    '/images/portfolio/bespoke-navy-pinstripe-3piece.jpg',
    'Best Seller',
    'A classic navy pinstripe 3-piece suit featuring expert tailoring and premium Super 150s wool. Perfect for corporate and formal occasions.',
    NULL,
    NULL,
    '[{"name":"Navy","value":"#1a1a4e"},{"name":"Charcoal","value":"#2c2c2c"},{"name":"Dark Brown","value":"#3b2f2f"}]'::jsonb,
    '["S","M","L","XL","XXL"]'::jsonb,
    'BRM-NAVY-3PC-001',
    'active',
    25
  ),
  (
    'Burnt Orange Double-Breasted',
    'Bespoke Suits',
    'Premium Italian Wool',
    'KES 17,000',
    17000.00,
    '/images/portfolio/bespoke-burnt-orange-double-breasted.jpg',
    'New',
    'A bold burnt orange double-breasted suit that commands attention. Crafted from premium Italian wool with meticulous tailoring.',
    NULL,
    NULL,
    '[{"name":"Burnt Orange","value":"#cc5500"},{"name":"Burgundy","value":"#722F37"},{"name":"Charcoal","value":"#2c2c2c"}]'::jsonb,
    '["S","M","L","XL","XXL"]'::jsonb,
    'BRM-ORNG-DB-002',
    'active',
    18
  ),
  (
    'Ivory Double-Breasted Set',
    'Bespoke Suits',
    'Fine Linen-Wool Blend',
    'KES 19,000',
    19000.00,
    '/images/portfolio/bespoke-cream-brown-mannequin-double.jpg',
    NULL,
    'An elegant ivory double-breasted set ideal for weddings and upscale events. Tailored from a luxurious linen-wool blend for comfort and sophistication.',
    NULL,
    NULL,
    '[{"name":"Ivory","value":"#f5f0e1"},{"name":"Champagne","value":"#d4c5a9"},{"name":"Navy","value":"#1a1a2e"}]'::jsonb,
    '["S","M","L","XL","XXL"]'::jsonb,
    'BRM-IVRY-DB-003',
    'active',
    15
  ),
  (
    'Camel Tuxedo with Bowtie',
    'Tuxedos',
    'Cashmere-Wool Blend',
    'KES 21,000',
    21000.00,
    '/images/portfolio/bespoke-tan-double-breasted-studio.jpg',
    'Popular',
    'A distinguished camel tuxedo paired with a matching bowtie. Crafted from a luxurious cashmere-wool blend for an unforgettable evening look.',
    NULL,
    NULL,
    '[{"name":"Camel","value":"#c19a6b"},{"name":"Ivory","value":"#f5f0e1"},{"name":"Charcoal","value":"#2c2c2c"}]'::jsonb,
    '["S","M","L","XL","XXL"]'::jsonb,
    'BRM-CAML-TUX-004',
    'active',
    12
  ),
  (
    'Houndstooth 3-Piece Vest Set',
    'Bespoke Suits',
    'Tweed Wool',
    'KES 23,000',
    23000.00,
    '/images/portfolio/bespoke-houndstooth-brown-vest-3piece.jpg',
    NULL,
    'A refined houndstooth 3-piece suit with a standout vest. Classic tweed wool construction for timeless British-inspired style.',
    NULL,
    NULL,
    '[{"name":"Houndstooth Grey","value":"#8B8589"},{"name":"Brown","value":"#3b2f2f"},{"name":"Navy","value":"#1a1a2e"}]'::jsonb,
    '["S","M","L","XL","XXL"]'::jsonb,
    'BRM-HOUND-3PC-005',
    'active',
    20
  ),
  (
    'Senator Burgundy Embroidered',
    'Senator Suits',
    'Premium Cotton-Silk Blend',
    'KES 25,000',
    25000.00,
    '/images/portfolio/senator-burgundy-embroidered-cap.jpg',
    'Limited',
    'A regal burgundy senator suit with intricate embroidery details and matching cap. Perfect for cultural events and distinguished occasions.',
    NULL,
    NULL,
    '[{"name":"Burgundy","value":"#722F37"},{"name":"Black","value":"#2c2c2c"},{"name":"White","value":"#f5f0e1"}]'::jsonb,
    '["S","M","L","XL","XXL"]'::jsonb,
    'BRM-SENR-BURG-006',
    'active',
    10
  ),
  (
    'Kaunda Teal Blue Safari',
    'Safari Suits',
    'Lightweight Cotton Blend',
    'KES 27,000',
    27000.00,
    '/images/portfolio/kaunda-teal-blue-safari.jpg',
    NULL,
    'A sharp teal blue Kaunda safari suit blending African heritage with modern tailoring. Lightweight and breathable for warm climates.',
    NULL,
    NULL,
    '[{"name":"Teal","value":"#008080"},{"name":"Charcoal","value":"#3b3b3b"},{"name":"Navy","value":"#1a1a2e"}]'::jsonb,
    '["S","M","L","XL","XXL"]'::jsonb,
    'BRM-KAUN-TEAL-007',
    'active',
    14
  ),
  (
    'White Textured 3-Piece',
    'Bespoke Suits',
    'Textured Jacquard Wool',
    'KES 30,000',
    30000.00,
    '/images/portfolio/bespoke-white-textured-3piece.jpg',
    'New',
    'A stunning white textured 3-piece suit with jacquard weave detailing. The ultimate statement piece for weddings and high-profile events.',
    NULL,
    NULL,
    '[{"name":"White","value":"#f5f5f5"},{"name":"Gold","value":"#c9a96e"},{"name":"Navy","value":"#1a1a4e"}]'::jsonb,
    '["S","M","L","XL","XXL"]'::jsonb,
    'BRM-WHT-3PC-008',
    'active',
    16
  );
